# Genera il database dei personaggi e dei luoghi dell'anno 1 (videogioco "I cinque duchi")
import json
EPOCHE = {
 "E1": "Ferrara delle origini (fino al X secolo)",
 "E2": "Ferrara medievale e comunale (X secolo - 1264)",
 "E3": "Ferrara degli Este: la signoria (1264 - metà del XV secolo)",
 "E4": "Ferrara rinascimentale e ducale (1450 - 1598)",
 "E5": "Ferrara dello Studio e delle scienze (1391 - XVI secolo, trasversale)",
 "E6": "Ferrara pontificia, napoleonica e risorgimentale (1598 - 1860)",
 "E7": "Ferrara del Novecento (1860 - 1995)",
 "E8": "Ferrara contemporanea (1995 - oggi)",
}
# id, nome, categoria del luogo-hub (hub=True se "mappa" tematica)
LUOGHI = [
 ("L01","Il Po e il territorio: Po di Volano, Valli di Comacchio, terre di bonifica",False,"Il territorio come personaggio"),
 ("L02","Cattedrale di San Giorgio",False,""),
 ("L03","Basilica di San Giorgio fuori le mura",False,""),
 ("L04","Abbazia di Pomposa (Codigoro)",False,""),
 ("L05","Palazzo Municipale (già Palazzo Ducale) e Piazza della Cattedrale",False,""),
 ("L06","Piazza delle Erbe (Trento Trieste) e centro medievale (via delle Volte)",False,""),
 ("L07","Monastero di Sant'Antonio in Polesine",True,"Mappa della lunga durata"),
 ("L08","Castello Estense",True,"Mappa del potere"),
 ("L09","Palazzo Paradiso (Biblioteca Comunale Ariostea)",True,"Mappa delle idee"),
 ("L10","Palazzo Schifanoia (Salone dei Mesi)",False,""),
 ("L11","Certosa di Ferrara (chiesa di San Cristoforo e cimitero monumentale)",True,"Mappa della memoria"),
 ("L12","Palazzo dei Diamanti e Pinacoteca Nazionale",False,""),
 ("L13","Addizione Erculea e Quadrivio degli Angeli",False,""),
 ("L14","Casa di Ludovico Ariosto",False,""),
 ("L15","Monastero del Corpus Domini (sepolture estensi)",False,""),
 ("L16","Palazzina Marfisa d'Este",False,""),
 ("L17","Antico Ospedale di Sant'Anna (prigionia di Tasso)",False,""),
 ("L18","Vicolo del Chiozzino",True,"Mappa dell'incertezza"),
 ("L19","Teatro Comunale",False,""),
 ("L20","Museo del Risorgimento e della Resistenza",False,""),
 ("L21","Mura di Ferrara",False,""),
 ("L22","Ex ghetto (via Mazzini, via Vignatagliata, via Vittoria) e sinagoghe",False,""),
 ("L23","MEIS - Museo Nazionale dell'Ebraismo Italiano e della Shoah",False,""),
 ("L24","Cimitero ebraico di via delle Vigne",False,""),
 ("L25","Polo chimico di Pontelagoscuro e Centro Ricerche Giulio Natta",True,"Mappa della modernità"),
 ("L26","Palazzo Massari (Gallerie d'Arte Moderna e Contemporanea)",False,""),
 ("L27","Casa Museo Remo Brindisi (Lido di Spina)",False,""),
 ("L28","Stadio Paolo Mazza",False,""),
 ("L29","Museo Civico di Storia Naturale e largo intitolato a Florestano Vancini",False,""),
 ("L30","Muretto del Castello e corso Martiri della Libertà (eccidio del 15 novembre 1943)",False,""),
 ("L31","Voghenza (antica sede diocesana)",False,""),
 ("L32","Comacchio e le Valli (Mandriole, trafila garibaldina del 1849)",False,""),
]
FONTI_BASE = ["Treccani, Enciclopedia e Dizionario Biografico degli Italiani (voce corrispondente)"]
# Campi: id, nome, periodo, inizio, fine, tipo, categorie, epoca, luogo, luoghi_sec, legame(A-E), certezza, evento, domanda, collegati, livello, note_verifica, fonti_extra, origine
P = [
("P01","San Maurelio","VII secolo (tradizione)",None,None,"persona",["religione","memoria"],"E1","L02",["L31"],"C",["D","M"],
 "Vescovo e patrono della tradizione ferrarese: la sua figura intreccia storia, agiografia e culto",
 "Quando una storia fa parte dell'identità di una comunità, possiamo studiarla anche se non tutto è verificabile?",["P02","P92"],"1-1","Grado di documentazione della biografia da precisare con fonti diocesane.",["Arcidiocesi di Ferrara-Comacchio"],"Pietro"),
("P02","San Giorgio","tarda antichità (culto)",None,None,"figura_leggendaria",["religione","memoria"],"E1","L03",["L02"],"D",["M","L"],
 "Santo patrono della città; il culto dà il nome alla basilica e alla cattedrale",
 "Una figura storicamente difficile da ricostruire può avere comunque un'enorme importanza culturale?",["P01"],None,"",[],"Pietro"),
("P03","Guido Monaco (Guido d'Arezzo) a Pomposa","XI secolo",None,None,"persona",["musica","religione"],"E2","L04",[],"A",["D"],
 "Monaco a Pomposa, elabora la notazione su righe che rende trasmissibile la musica",
 "Come sopravvive una conoscenza quando deve essere copiata e trasmessa a mano?",["P90"],"1-2","Periodo pomposiano e sua datazione da verificare.",[],"Pietro"),
("P04","Matilde di Canossa","1046-1115",1046,1115,"persona",["politica"],"E2","L01",[],"D",["D"],
 "Ferrara entra nella sfera dei Canossa; alla morte di Matilde (1115) si consolida il Comune",
 "Quanto può essere potente una persona senza possedere direttamente una città?",["P05","P06"],"1-3","",[],"Pietro"),
("P05","Gli Adelardi (famiglia)","XII secolo",None,None,"gruppo",["politica"],"E2","L06",[],"D",["D","C"],
 "Famiglia guelfa protagonista del Comune",
 "Chi aveva il potere prima degli Este?",["P06","P08"],"1-3","Scheda aggiunta: citati nella narrazione.",[],"aggiunta"),
("P06","Salinguerra Torelli","XIII secolo",None,1244,"persona",["politica"],"E2","L05",["L06"],"D",["D","I"],
 "Capo della parte ghibellina, rivale degli Este",
 "Come cambia la storia quando ascoltiamo anche la parte che alla fine ha perso?",["P05","P08"],"1-3","Distinguere Salinguerra I e Salinguerra II; data di morte da verificare.",[],"Pietro"),
("P07","Obizzo I d'Este","XII secolo",None,1193,"persona",["politica"],"E2","L08",[],"D",["D","I"],
 "Prima presenza estense nelle vicende ferraresi",
 "Come diventa una famiglia aristocratica una famiglia di governo?",["P08"],None,"Il legame diretto con Ferrara va precisato. Il luogo è simbolico: il Castello è del 1385.",[],"Pietro"),
("P08","Azzo VI d'Este","1170-1212",1170,1212,"persona",["politica"],"E2","L05",[],"D",["D"],
 "Assume il controllo della città all'inizio del XIII secolo",
 "Quando il potere politico diventa davvero riconosciuto?",["P06","P07"],"1-4","",[],"Pietro"),
("P09","Aldobrandino d'Este","XIII-XIV secolo",None,None,"persona",["politica"],"E3","L05",[],"D",["D"],
 "Successioni e conflitti dinastici",
 "Chi decide chi ha diritto a ereditare il potere?",["P12"],None,"Non è chiaro quale Aldobrandino si intenda (I, morto nel 1215, o i successivi): numerazione da verificare.",[],"Pietro"),
("P10","Azzo VII d'Este (Novello)","1205-1264",1205,1264,"persona",["politica"],"E2","L05",["L07"],"D",["D"],
 "Consolida il potere estense contro Salinguerra; padre della beata Beatrice II",
 "Quanto conta una vittoria militare per fondare un potere duraturo?",["P06","P11","P12"],None,"Scheda aggiunta: citato nella narrazione ma privo di scheda.",[],"aggiunta"),
("P11","Beata Beatrice II d'Este","m. 1262",None,1262,"persona",["religione","memoria"],"E2","L07",[],"A",["D","M"],
 "Figlia di Azzo VII; la sua vicenda è legata alla comunità benedettina di Sant'Antonio in Polesine, dove si conserva la tomba",
 "La storia di una famiglia potente coincide con la storia di chi esercita formalmente il potere?",["P10","P91","P35"],"1-5","Data di fondazione del monastero (tradizionalmente 1257) da verificare.",["MuseoFerrara"],"Pietro"),
("P12","Obizzo II d'Este","1247-1293",1247,1293,"persona",["politica"],"E3","L05",["L08"],"D",["D"],
 "Nel 1264 è riconosciuto signore di Ferrara: nasce la signoria",
 "Che differenza c'è tra governare una città e diventarne signore?",["P10","P09"],"1-6","Il Castello (1385) è successivo: il luogo vale come simbolo del potere.",[],"Pietro"),
("P13","Obizzo III d'Este","1294-1352",1294,1352,"persona",["politica"],"E3","L06",[],"D",["D"],
 "Passaggio dal dominio personale alla costruzione di istituzioni",
 "Come si vede il potere nella vita quotidiana?",["P12"],None,"",[],"Pietro"),
("P14","Azzo VIII d'Este","m. 1308",None,1308,"persona",["politica"],"E3","L05",[],"D",["D"],
 "Crisi successoria alla sua morte e intervento papale e veneziano",
 "Che cosa succede a un potere quando manca un erede riconosciuto?",["P12","P58"],None,"Scheda aggiunta: citato nella narrazione. Utile come anticipazione della Devoluzione.",[],"aggiunta"),
("P15","Nicolò II d'Este","1338-1388",1338,1388,"persona",["politica","architettura"],"E3","L08",[],"A",["D"],
 "Dopo la rivolta del 1385 fa costruire il Castello di San Michele, cioè il Castello Estense",
 "Perché una città costruisce una fortezza dentro se stessa?",["P16"],"1-7","",["Castello Estense"],"Pietro"),
("P16","Alberto V d'Este","1347-1393",1347,1393,"persona",["politica","istruzione"],"E3","L09",[],"C",["D"],
 "Nel 1391 ottiene da papa Bonifacio IX la bolla di fondazione dello Studio",
 "Che cosa succede a una città quando comincia ad attirare persone da fuori per studiare?",["P89"],"1-8","Palazzo Paradiso diventa sede dello Studio solo più tardi (XVI secolo): il legame con il luogo è di memoria, non di vita.",["Università degli Studi di Ferrara"],"Pietro"),
("P17","Nicolò III d'Este","1383-1441",1383,1441,"persona",["politica"],"E3","L08",[],"A",["D","M"],
 "Apre la grande stagione estense; la vicenda di Parisina (1425) diventa poi materia letteraria",
 "Come si trasforma un fatto di cronaca di corte in una storia romantica?",["P18","P22","P19"],"1-9","Scheda aggiunta: citato nella narrazione.",[],"aggiunta"),
("P18","Leonello d'Este","1407-1450",1407,1450,"persona",["politica","cultura"],"E3","L05",[],"A",["D"],
 "Usa la cultura come strumento di prestigio politico",
 "Quanto di ciò che attribuiamo a un protagonista è stato preparato da chi è venuto prima?",["P19","P20","P21","P22"],"1-10","",[],"Pietro"),
("P19","Guarino Veronese","1374-1460",1374,1460,"persona",["istruzione","letteratura"],"E3","L09",["L08"],"A",["D"],
 "Maestro umanista alla corte estense e nello Studio; insegna greco e latino",
 "Quanto di una cultura dipende dalle persone che insegnano?",["P18","P17"],"1-9","Il Palazzo dei Diamanti indicato nel materiale è posteriore alla morte di Guarino (costruito dal 1493): luogo corretto.",[],"Pietro"),
("P20","Leon Battista Alberti","1404-1472",1404,1472,"persona",["architettura","scienza","crittografia"],"E3","L05",[],"B",["D"],
 "Frequenta la corte di Leonello; autore del De cifris (1467), con il primo cifrario polialfabetico a disco",
 "Chi ha il diritto di leggere un messaggio?",["P18"],"1-10","Scheda aggiunta. Il legame con Ferrara (monumento equestre a Nicolò III, rapporti con Leonello) va precisato.",[],"aggiunta"),
("P21","Pisanello","c. 1395-1455",1395,1455,"persona",["arte"],"E3","L08",[],"D",["D"],
 "Ritratti e medaglie di Leonello: il ritratto come strumento politico",
 "Un ritratto mostra una persona o costruisce un'immagine della persona?",["P18"],None,"Il ritratto di Leonello non è conservato a Ferrara (Accademia Carrara, Bergamo): il luogo è simbolico.",[],"Pietro"),
("P22","Borso d'Este","1413-1471",1413,1471,"persona",["politica","cultura"],"E4","L10",["L08","L11","L05"],"B",["D"],
 "Duca di Modena e Reggio dal 1452, duca di Ferrara nel 1471 per concessione di papa Paolo II; fonda la Certosa; committente di Schifanoia e della Bibbia di Borso",
 "Quanto dell'immagine di un sovrano viene costruito dal sovrano stesso?",["P18","P23","P24","P25","P26","P27"],"1-12","Protagonista narrativo e narratore dell'anno 1.",[],"Pietro"),
("P23","Cosmè Tura","c. 1430-1495",1430,1495,"persona",["arte"],"E4","L12",[],"B",["D"],
 "Capostipite dell'Officina ferrarese",
 "Come può un'intera città sviluppare una propria identità artistica?",["P24","P25"],"1-13","",[],"Pietro"),
("P24","Francesco del Cossa","c. 1436-1478",1436,1478,"persona",["arte"],"E4","L10",[],"B",["D"],
 "Affreschi del Salone dei Mesi a Palazzo Schifanoia",
 "Chi decide che cosa deve essere rappresentato?",["P22","P26"],"1-12","",[],"Pietro"),
("P25","Ercole de' Roberti","c. 1451-1496",1451,1496,"persona",["arte"],"E4","L10",["L12"],"B",["D"],
 "Innovazione della scuola ferrarese",
 "Quanto nasce un'innovazione da un singolo artista e quanto dall'ambiente in cui lavora?",["P24"],"1-12","",[],"Pietro"),
("P26","Pellegrino Prisciani","c. 1435-1518",1435,1518,"persona",["scienza","archivi"],"E4","L10",[],"B",["D","I"],
 "Astrologo, bibliotecario e archivista estense, a cui si attribuisce il programma iconografico del Salone dei Mesi",
 "Chi è l'autore di un'opera collettiva?",["P24","P22"],"1-12","Scheda aggiunta. L'attribuzione del programma di Schifanoia è discussa.",[],"aggiunta"),
("P27","Taddeo Crivelli e i miniatori della Bibbia di Borso","1455-1461",1455,1461,"gruppo",["arte"],"E4","L12",[],"B",["D"],
 "Miniano la Bibbia di Borso, oggi alla Biblioteca Estense di Modena",
 "Perché un'opera nata a Ferrara si trova oggi in un'altra città?",["P22"],"1-13","Scheda aggiunta. La Bibbia è conservata a Modena: aggancio utile con la Devoluzione (1-22).",[],"aggiunta"),
("P28","Tito Vespasiano Strozzi","1424-1505",1424,1505,"persona",["letteratura","politica"],"E4","L05",[],"A",["D"],
 "Poeta umanista e funzionario della corte",
 "Quanto è libero un intellettuale quando dipende da una corte?",["P29"],None,"Il luogo \"Palazzo Strozzi\" indicato nel materiale va identificato.",[],"Pietro"),
("P29","Matteo Maria Boiardo","1441-1494",1441,1494,"persona",["letteratura"],"E4","L08",[],"D",["D"],
 "Scrive l'Orlando innamorato",
 "Una storia inventata può diventare parte della cultura reale di una società?",["P37"],"1-17","",[],"Pietro"),
("P30","Ercole I d'Este","1431-1505",1431,1505,"persona",["politica","urbanistica"],"E4","L13",["L12","L15"],"B",["D"],
 "Promuove l'Addizione Erculea (dal 1492); accoglie esuli sefarditi; mecenate musicale (Josquin)",
 "Quanto può trasformare una città la visione di un singolo governante?",["P31","P33","P88"],"1-14","Protagonista dell'anno 2 secondo la cornice del curricolo.",[],"Pietro"),
("P31","Biagio Rossetti","c. 1447-1516",1447,1516,"persona",["architettura","urbanistica"],"E4","L13",["L12"],"B",["D"],
 "Progetta l'Addizione Erculea e il Palazzo dei Diamanti",
 "Quando progettiamo una città, per chi la stiamo progettando?",["P30"],"1-14","",["Ferrara Terra e Acqua"],"Pietro"),
("P32","Isabella d'Este","1474-1539",1474,1539,"persona",["politica","cultura"],"E4","L08",[],"D",["D"],
 "Nata a Ferrara, marchesa di Mantova: potere femminile e reti dinastiche",
 "Potere formale e influenza sono la stessa cosa?",["P30","P36"],None,"La sua attività si svolge soprattutto a Mantova: il legame con Ferrara è di origine.",[],"Pietro"),
("P33","Josquin des Prez","c. 1450-1521",1450,1521,"persona",["musica"],"E4","L05",[],"B",["D"],
 "Maestro di cappella di Ercole I (1503-1504); la Missa Hercules Dux Ferrariae ricava il tema dalle vocali del nome del duca (soggetto cavato)",
 "Un nome può diventare musica? Che cos'è una codifica?",["P30"],None,"Scheda aggiunta: aggancio per la codifica del testo (1-9) e per l'anno 2.",[],"aggiunta"),
("P34","Girolamo Savonarola","1452-1498",1452,1498,"persona",["religione","politica"],"E4","L06",[],"A",["D","M"],
 "Nato a Ferrara, predicatore a Firenze",
 "Una persona appartiene al luogo in cui nasce o a quelli in cui agisce?",[],None,"Scheda aggiunta. Casa natale in via Savonarola: da verificare.",[],"aggiunta"),
("P35","Lucrezia Borgia","1480-1519",1480,1519,"persona",["politica","cultura","memoria"],"E4","L15",["L08","L16"],"C",["D","M"],
 "Nel 1502 arriva a Ferrara come moglie di Alfonso I; è sepolta nel Corpus Domini. La sua figura è stata trasformata nel tempo da propaganda, letteratura e mito",
 "Come nasce un mito storico? Chi era Lucrezia e chi è diventata nella memoria degli altri?",["P36","P11","P57"],"1-16","La Palazzina Marfisa fu voluta dal figlio Francesco d'Este: il legame è indiretto.",[],"Pietro"),
("P36","Alfonso I d'Este","1476-1534",1476,1534,"persona",["politica","tecnica","arte"],"E4","L08",["L15"],"A",["D"],
 "Duca-artigliere e fonditore; committente del Camerino d'alabastro; protegge Ariosto",
 "Quando una tecnologia cambia la guerra, chi ne porta la responsabilità?",["P35","P37","P48"],"1-18","Scheda aggiunta: è uno dei cinque duchi (protagonista dell'anno 3).",[],"aggiunta"),
("P37","Ludovico Ariosto","1474-1533",1474,1533,"persona",["letteratura"],"E4","L14",["L09"],"A",["D"],
 "Lavora nella corte estense e scrive l'Orlando furioso (1516-1532); la tomba è a Palazzo Paradiso",
 "Possiamo distinguere ciò che un narratore racconta da ciò che il narratore pensa?",["P29","P36"],"1-17","",[],"Pietro"),
("P38","Niccolò Leoniceno","1428-1524",1428,1524,"persona",["medicina","filologia"],"E5","L09",[],"C",["D"],
 "Medico e filologo: corregge gli errori degli autori antichi (Plinio)",
 "Che cosa dobbiamo fare quando ciò che osserviamo sembra contraddire un'autorità antica?",["P39","P44"],"1-19","",["Università degli Studi di Ferrara"],"Pietro"),
("P39","Giovanni Manardo","1462-1536",1462,1536,"persona",["medicina"],"E5","L09",[],"C",["D"],
 "Medicina e trasformazione del sapere",
 "Come si passa dalla conoscenza tramandata alla conoscenza verificata?",["P38"],"1-19","",[],"Pietro"),
("P40","Ludovico Bonaccioli","c. 1475-1537",1475,1537,"persona",["medicina"],"E5","L09",[],"C",["D"],
 "Medico di corte, studi sul corpo umano",
 "Come cambia una società quando cambia il modo in cui interpreta il corpo?",["P35"],None,"",[],"Pietro"),
("P41","Celio Calcagnini","1479-1541",1479,1541,"persona",["letteratura","scienza"],"E5","L09",[],"C",["D"],
 "Umanista e scienziato; scrive sul moto della Terra",
 "Siamo noi a dividere la conoscenza in discipline?",["P42"],"1-15","",[],"Pietro"),
("P42","Niccolò Copernico","1473-1543",1473,1543,"persona",["scienza","astronomia"],"E5","L09",[],"C",["D"],
 "Nel 1503 si laurea in diritto canonico a Ferrara",
 "Quanto siamo disposti a mettere in discussione una visione del mondo che sembra ovvia?",["P41"],"1-15","La laurea avviene prima che lo Studio abbia sede a Palazzo Paradiso: il legame con il luogo è di memoria.",["Università degli Studi di Ferrara"],"Pietro"),
("P43","Paracelso","1493-1541",1493,1541,"persona",["medicina","chimica"],"E5","L09",[],"C",["D","I"],
 "Legato agli ambienti medici dello Studio; la sua laurea ferrarese è discussa",
 "Una teoria nuova va accettata perché è rivoluzionaria o valutata per le prove che porta?",["P38"],"1-19","Il conseguimento del titolo a Ferrara è controverso: ottimo caso per l'etichetta I.",[],"Pietro"),
("P44","Antonio Musa Brasavola","1500-1555",1500,1555,"persona",["medicina","botanica"],"E5","L09",[],"C",["D"],
 "Medicina, botanica e farmacia",
 "Come si trasforma un sapere quando viene sottoposto a osservazione e pratica?",["P38"],"1-19","",[],"Pietro"),
("P45","Gabriele Falloppio","1523-1562",1523,1562,"persona",["medicina","anatomia"],"E5","L09",[],"C",["D"],
 "Anatomia e osservazione",
 "Che cosa rende più convincente un'osservazione rispetto all'autorità di un testo?",["P46"],"1-19","",[],"Pietro"),
("P46","Giovanni Battista Canani","1515-1579",1515,1579,"persona",["medicina","anatomia"],"E5","L09",[],"C",["D"],
 "Anatomia: tavole anatomiche",
 "Una rappresentazione scientifica è la realtà o un modello della realtà?",["P45"],"1-19","",[],"Pietro"),
("P47","Benvenuto Tisi detto il Garofalo","c. 1481-1559",1481,1559,"persona",["arte"],"E4","L12",["L02"],"B",["D"],
 "La pittura ferrarese nel pieno Rinascimento",
 "Quando uno stile diventa riconoscibile come appartenente a una città?",["P48"],None,"Nome proprio: Benvenuto Tisi (nel materiale compare \"Beniamino\").",[],"Pietro"),
("P48","Dosso Dossi","c. 1486-1542",1486,1542,"persona",["arte"],"E4","L12",["L08"],"B",["D"],
 "Pittore della corte di Alfonso I",
 "Un artista che lavora per una corte è un artista indipendente?",["P36"],None,"",[],"Pietro"),
("P49","Ercole II d'Este","1508-1559",1508,1559,"persona",["politica"],"E4","L08",[],"A",["D"],
 "Duca dal 1534; marito di Renata di Francia",
 "Si può governare uno Stato cattolico con una corte aperta alla Riforma?",["P50","P36","P51"],"1-20","Scheda aggiunta: è uno dei cinque duchi (protagonista dell'anno 4).",[],"aggiunta"),
("P50","Renata di Francia","1510-1575",1510,1575,"persona",["politica","religione"],"E4","L08",[],"A",["D"],
 "Porta a corte idee della Riforma; ospita Calvino (1536); tensioni con Roma",
 "La cultura è mai completamente separata dalla politica?",["P49"],"1-20","Scheda aggiunta: citata nella narrazione.",[],"aggiunta"),
("P51","Alfonso II d'Este","1533-1597",1533,1597,"persona",["politica","musica"],"E4","L08",["L17"],"A",["D"],
 "Ultimo duca a Ferrara; corte musicale; terremoto del 1570; muore senza erede legittimo riconosciuto",
 "Che cosa succede a una città costruita attorno a una corte quando la corte finisce?",["P52","P53","P54","P56","P58"],"1-21","Scheda aggiunta: è uno dei cinque duchi (protagonista dell'anno 5).",[],"aggiunta"),
("P52","Torquato Tasso","1544-1595",1544,1595,"persona",["letteratura"],"E4","L17",["L08"],"A",["D","M"],
 "Poeta della corte di Alfonso II, recluso a Sant'Anna dal 1579 al 1586",
 "Che cosa succede quando un artista non coincide con l'immagine che il pubblico costruisce di lui?",["P51"],"1-21","",[],"Pietro"),
("P53","Luzzasco Luzzaschi","c. 1545-1607",1545,1607,"persona",["musica"],"E4","L08",[],"A",["D"],
 "Musica di corte e concerto delle dame",
 "Quanto della cultura di una città rischiamo di perdere se conserviamo soprattutto edifici e documenti scritti?",["P54","P55"],"1-21","",[],"Pietro"),
("P54","Il concerto delle dame","anni 1580-1597",1580,1597,"gruppo",["musica"],"E4","L08",[],"A",["D","C"],
 "Ensemble di cantatrici professioniste della corte di Alfonso II",
 "Chi erano le musiciste di cui ricordiamo meno i nomi?",["P53","P51"],"1-21","Scheda aggiunta.",[],"aggiunta"),
("P55","Girolamo Frescobaldi","1583-1643",1583,1643,"persona",["musica"],"E4","L02",[],"D",["D"],
 "Nato a Ferrara, costruisce una carriera europea",
 "Una persona appartiene al luogo in cui nasce o ai luoghi nei quali costruisce la propria vita?",["P53"],None,"",[],"Pietro"),
("P56","Pirro Ligorio","c. 1512-1583",1512,1583,"persona",["architettura","scienza"],"E4","L08",[],"B",["D"],
 "Al servizio di Alfonso II, dopo il terremoto del 1570 scrive un trattato sui terremoti con proposte di edilizia antisismica",
 "Si può imparare da una catastrofe a costruire meglio?",["P51"],None,"Scheda aggiunta: aggancio per la simulazione dell'anno 5.",[],"aggiunta"),
("P57","Marfisa d'Este","c. 1554-1608",1554,1608,"persona",["politica","memoria"],"E4","L16",[],"A",["D","L"],
 "Dà il nome alla palazzina; attorno a lei fiorisce una leggenda popolare",
 "Perché certe persone diventano protagoniste di leggende?",["P35"],None,"Scheda aggiunta.",[],"aggiunta"),
("P58","Papa Clemente VIII e la Devoluzione","1598",1598,1598,"persona",["politica","religione"],"E6","L05",["L21"],"D",["D"],
 "Rivendica Ferrara come feudo pontificio: nel 1598 gli Este si trasferiscono a Modena",
 "Una città che perde la propria corte scompare o si reinventa?",["P51"],"1-22","Scheda aggiunta.",["Università di Ferrara, studi sulla Devoluzione"],"aggiunta"),
("P59","Bartolomeo Chiozzi, il \"Mago Chiozzino\"","1671-1741",1671,1741,"persona",["scienza","memoria","leggenda"],"E6","L18",[],"E",["D?","L","F"],
 "Ingegnere idraulico nato a Mantova, vissuto appartato a Ferrara; la fama di mago nasce dalle sue attività scientifiche; Bacchelli lo trasforma in personaggio del Mulino del Po; il vicolo gli è intitolato nel 1967",
 "Se una leggenda nasce da una persona realmente esistita, dove finisce la storia e dove comincia la leggenda?",["P60","P61"],"1-23","Dati biografici da fonte enciclopedica aperta (Wikipedia): verificare su fonti d'archivio. Collegamento con Bonati: entrambi uomini delle acque.",["Wikipedia, voci \"Bartolomeo Chiozzi\" e \"Vicolo del Chiozzino\""],"Pietro"),
("P60","Riccardo Bacchelli","1891-1985",1891,1985,"persona",["letteratura"],"E7","L18",["L01"],"D",["D"],
 "Con Il mulino del Po trasforma la storia del territorio ferrarese in romanzo",
 "Che cosa aggiunge un romanziere a una storia vera?",["P59"],"1-29","Scheda aggiunta: indispensabile per la missione del Chiozzino.",[],"aggiunta"),
("P61","Teodoro Bonati","1724-1820",1724,1820,"persona",["matematica","ingegneria","territorio"],"E6","L01",["L11"],"C",["D"],
 "Matematico e ingegnere idraulico: le acque, le bonifiche, il Po",
 "La natura deve essere dominata oppure compresa e governata insieme alle esigenze umane?",["P59","P92","P83"],"1-24","Monumento in Certosa da verificare.",[],"Pietro"),
("P62","Antonio Foschini","1741-1813",1741,1813,"persona",["architettura"],"E6","L19",["L11"],"B",["D"],
 "Progetta con Cosimo Morelli il Teatro Comunale",
 "Dove finisce l'arte e dove comincia la tecnica?",["P63"],"1-25","",[],"Pietro"),
("P63","Napoleone e l'età francese","1796-1814",1796,1814,"persona",["politica"],"E6","L05",[],"D",["D","I"],
 "Nel 1796 i francesi entrano a Ferrara: Repubblica Cispadana, Cisalpina, Regno d'Italia; nuove idee e nuove istituzioni, ma anche requisizioni e confische",
 "La stessa trasformazione può essere vista da punti di vista diversi?",["P62"],"1-25","Scheda aggiunta: la narrazione tratta il periodo senza scheda.",[],"aggiunta"),
("P64","Ugo Bassi","1801-1849",1801,1849,"persona",["religione","politica"],"E6","L20",[],"D",["D","M"],
 "Barnabita nato a Cento, cappellano dei volontari, fucilato nel 1849",
 "Quando un ideale politico diventa parte dell'identità personale?",["P66"],"1-26","",[],"Pietro"),
("P65","Tancredi Mosti Trotti Estense","1812-1869",1812,1869,"persona",["politica","militare"],"E6","L20",[],"C",["D"],
 "Comandante dei Bersaglieri del Po",
 "Come si forma un'identità politica collettiva?",["P66"],"1-26","Date da verificare.",[],"Pietro"),
("P66","I Bersaglieri del Po","1848-1849",1848,1849,"gruppo",["politica","militare","memoria"],"E6","L20",["L21"],"C",["C","M"],
 "Corpo volontario ferrarese del 1848",
 "Che cosa significava essere italiani prima che esistesse l'Italia unita? Quando un gruppo diventa simbolo, che cosa rischiamo di dimenticare?",["P65","P64"],"1-26","",[],"Pietro"),
("P67","Domenico Malagutti","m. 1853",None,1853,"persona",["politica","memoria"],"E6","L20",[],"C",["D","M"],
 "Uno dei tre martiri fucilati a Ferrara il 16 marzo 1853",
 "Chi decide quali morti diventano simboli pubblici?",["P68","P69"],"1-26","Data dell'esecuzione da verificare.",[],"Pietro"),
("P68","Giacomo Succi","m. 1853",None,1853,"persona",["politica","memoria"],"E6","L20",[],"C",["D","M"],
 "Martire del 1853",
 "La memoria pubblica racconta tutti nello stesso modo?",["P67","P69"],"1-26","",[],"Pietro"),
("P69","Luigi Parmeggiani","m. 1853",None,1853,"persona",["politica","memoria"],"E6","L20",[],"C",["D","M"],
 "Martire del 1853",
 "Che rapporto c'è fra un individuo e il mito patriottico costruito su di lui?",["P67","P68"],"1-26","",[],"Pietro"),
("P70","Gioacchino (Nino) Bonnet","XIX secolo",None,None,"persona",["politica","memoria"],"E6","L32",[],"D",["D","M"],
 "Probabilmente il patriota comacchiese che nel 1849 aiutò Garibaldi a sfuggire agli austriaci nelle Valli, dopo la morte di Anita",
 "Quanto conta chi aiuta, rispetto a chi viene ricordato come eroe?",["P66"],"1-26","IDENTITÀ DA VERIFICARE: il materiale lo indica come \"memoria culturale, Certosa\". A Ferrara esiste via Nino Bonnet; l'identificazione con il Bonnet della trafila garibaldina è un'ipotesi di Claude da controllare.",[],"Pietro (ricollocato)"),
("P71","Giovanni Boldini","1842-1931",1842,1931,"persona",["arte"],"E7","L11",["L26"],"C",["D"],
 "Parte da Ferrara per una carriera internazionale; sepolto in Certosa",
 "Quanto della propria identità una persona porta con sé quando lascia la propria città?",["P72","P74"],None,"",[],"Pietro"),
("P72","Gaetano Previati","1852-1920",1852,1920,"persona",["arte"],"E7","L26",["L11"],"B",["D"],
 "Porta Ferrara nella modernità pittorica",
 "Un'opera deve assomigliare alla realtà per rappresentarla?",["P71"],None,"",[],"Pietro"),
("P73","Giorgio de Chirico","1888-1978",1888,1978,"persona",["arte"],"E7","L12",[],"D",["D"],
 "A Ferrara negli anni della prima guerra mondiale: la pittura metafisica",
 "Quando un artista rappresenta una città, rappresenta la città o il proprio modo di percepirla?",["P74"],None,"",[],"Pietro"),
("P74","Filippo de Pisis","1896-1956",1896,1956,"persona",["arte","letteratura","scienze naturali"],"E7","L26",[],"B",["D"],
 "Attraversa letteratura, pittura, collezionismo, scienze naturali e cultura europea",
 "Una persona deve essere definita da una sola professione? Esiste una rappresentazione neutrale della realtà?",["P73","P82"],None,"",[],"Pietro"),
("P75","Corrado Govoni","1884-1965",1884,1965,"persona",["letteratura"],"E7","L11",[],"C",["D"],
 "Poeta ferrarese, tra crepuscolari e futuristi",
 "Come si racconta in poesia un paesaggio di pianura?",[],None,"Scheda aggiunta: citato nella lista della Certosa. Luogo di sepoltura da verificare.",[],"aggiunta"),
("P76","Carlo Savonuzzi","1897-1973",1897,1973,"persona",["architettura","ingegneria"],"E7","L11",[],"C",["D"],
 "Architettura e trasformazione urbana nel Novecento",
 "Come cambia una città quando la modernità interviene su una città storica?",[],None,"Date e sepoltura da verificare.",[],"Pietro"),
("P77","Alda Costa","1876-1944",1876,1944,"persona",["istruzione","politica"],"E7","L06",[],"D",["D"],
 "Maestra, socialista e antifascista",
 "Quanto può cambiare una società attraverso persone che educano ogni giorno senza diventare famose?",["P79"],"1-28","Luogo specifico (scuola, targa) da identificare.",[],"Pietro"),
("P78","Renzo Ravenna","1893-1961",1893,1961,"persona",["politica"],"E7","L05",["L22"],"A",["D","I"],
 "Podestà di Ferrara dal 1926 al 1938, ebreo: costretto a dimettersi dalle leggi razziali",
 "Come può una società passare dalla convivenza alla discriminazione?",["P88","P79"],"1-28","PROPOSTA DI CLAUDE, da approvare. È una figura complessa (fascista ed ebreo), da trattare con cura storiografica.",[],"proposta"),
("P79","Giorgio Bassani","1916-2000",1916,2000,"persona",["letteratura","memoria"],"E7","L24",["L22","L23","L30"],"C",["D","M"],
 "Costruisce una Ferrara letteraria della memoria; Una notte del '43; sepolto nel cimitero ebraico di via delle Vigne",
 "La Ferrara che ricordiamo è la stessa Ferrara che è esistita? Una città raccontata da uno scrittore è la stessa che troveremmo negli archivi?",["P81","P88","P77"],"1-28","",["Fondazione Giorgio Bassani"],"Pietro"),
("P80","Renata Viganò","1900-1976",1900,1976,"persona",["letteratura","memoria"],"E7","L32",[],"D",["D"],
 "Partigiana e scrittrice; L'Agnese va a morire è ambientato nelle Valli di Comacchio",
 "Che cosa cambia quando una persona trasforma la propria esperienza in letteratura?",["P79"],"1-28","Nata a Bologna: il legame è con il territorio provinciale (Valli), non con la città.",[],"Pietro"),
("P81","Florestano Vancini","1926-2008",1926,2008,"persona",["cinema","memoria"],"E7","L29",["L11","L30"],"C",["D","M"],
 "Con La lunga notte del '43 (1960) porta al cinema il racconto di Bassani",
 "Quando un film racconta un fatto storico, lo documenta o lo interpreta?",["P79","P82"],"1-28","Da verificare l'esatta collocazione del largo a lui intitolato.",[],"Pietro"),
("P82","Michelangelo Antonioni","1912-2007",1912,2007,"persona",["cinema"],"E7","L11",[],"C",["D","M"],
 "Porta nel cinema una Ferrara fatta di spazi, silenzi e periferie",
 "Quanto della realtà vediamo davvero quando guardiamo un'immagine? Un'inquadratura non è mai tutto il mondo.",["P81","P74"],"1-29","",[],"Pietro"),
("P83","Giulio Natta","1903-1979",1903,1979,"persona",["scienza","chimica","industria"],"E7","L25",[],"B",["D"],
 "Contribuisce nel 1938 al primo impianto italiano di gomma sintetica a Ferrara; ricerca sui polimeri e produzione del polipropilene isotattico; Nobel per la chimica 1963",
 "Quando una scoperta scientifica diventa tecnologia e quando industria? La scoperta appartiene solo allo scienziato?",["P61","P22"],"1-27","",["Centro Ricerche Giulio Natta"],"Pietro"),
("P84","Guido Carli","1914-1993",1914,1993,"persona",["economia","istituzioni"],"E7","L32",[],"D",["D"],
 "Governatore della Banca d'Italia e ministro; la famiglia è originaria di Comacchio",
 "Quanto resta legata al territorio d'origine una persona che entra nelle istituzioni nazionali?",[],None,"Nato a Brescia: il legame è con Comacchio (origine familiare), non con Ferrara città.",["Comune di Ferrara, Cronaca Comune 2022"],"Pietro"),
("P85","Remo Brindisi","1918-1996",1918,1996,"persona",["arte"],"E8","L27",[],"A",["D"],
 "Casa Museo al Lido di Spina: arte contemporanea e territorio provinciale",
 "Quando una collezione diventa patrimonio culturale?",[],"1-30","",[],"Pietro"),
("P86","Paolo Mazza","1901-1981",1901,1981,"persona",["sport","società"],"E7","L28",[],"C",["D","M"],
 "Presidente della SPAL; lo stadio porta il suo nome",
 "Quando qualcosa diventa parte dell'identità di una città, deve essere necessariamente un monumento?",[],"1-30","",[],"Pietro"),
("P87","Vasco Brondi","1984-",1984,None,"persona",["musica","società"],"E8","L25",[],"D",["D"],
 "Ferrara contemporanea raccontata attraverso la musica",
 "Chi racconta la propria città racconta la città o la propria esperienza della città?",[],"1-30","",[],"Pietro"),
("P88","La comunità ebraica ferrarese","dal Medioevo a oggi",None,None,"gruppo",["religione","società","memoria"],"E4","L23",["L22","L24"],"A",["C"],
 "Famiglie, commerci, professioni, cultura; rapporti con gli Este (accoglienza dei sefarditi); ghetto pontificio (1624); leggi razziali (1938); persecuzione e Shoah; memoria",
 "Come può una comunità appartenere a una città e mantenere una propria identità?",["P30","P79","P78"],"1-11","Da trattare come protagonista e non solo come capitolo della persecuzione. Il ghetto viene istituito nel 1624.",["MEIS"],"Pietro"),
("P89","Gli studenti dello Studio","XIV-XVI secolo",None,None,"gruppo",["istruzione"],"E5","L09",[],"A",["C"],
 "Persone che arrivano non per conquistare la città ma per imparare",
 "Che cosa succede a una città quando le persone arrivano per imparare?",["P16"],"1-8","",[],"Pietro"),
("P90","Mercanti, artigiani e cittadini","tutte le epoche",None,None,"gruppo",["società","economia"],"E2","L06",[],"A",["C"],
 "La vita quotidiana della città, oltre i governanti",
 "Come cambia la vita quotidiana quando cambia il potere?",[],"1-4","",[],"Pietro"),
("P91","Le monache di Sant'Antonio in Polesine","XIII secolo - oggi",None,None,"gruppo",["religione"],"E2","L07",[],"A",["C"],
 "Una storia al femminile e di lunga durata",
 "Come può un'istituzione sopravvivere per secoli cambiando insieme alla società?",["P11"],"1-5","",[],"Pietro"),
("P92","Il territorio del Po","tutte le epoche",None,None,"luogo_personaggio",["territorio"],"E1","L01",[],"D",["C"],
 "Il territorio condiziona agricoltura, trasporti, bonifiche, insediamenti, guerre, commerci, paesaggio",
 "È la società a trasformare il territorio o il territorio a trasformare la società?",["P61","P59"],"1-1","",[],"Pietro"),
("P93","La città stessa","tutte le epoche",None,None,"luogo_personaggio",["memoria"],"E8","L05",[],"D",["C"],
 "Ferrara come personaggio principale: una città fatta di strati di tempo",
 "Come facciamo a sapere che cosa è successo?",[],"1-30","",[],"Pietro"),
]
keys=["id","nome","periodo","anno_inizio","anno_fine","tipo","categorie","epoca","luogo_principale","luoghi_secondari","legame_luogo","certezza","evento_principale","domanda_critica","personaggi_collegati","livello_gioco","note_verifica","fonti_orientamento","origine"]
pers=[]
for t in P:
    d=dict(zip(keys,t)); d["fonti_orientamento"]=FONTI_BASE+d["fonti_orientamento"]
    d["ruolo_nel_gioco"]="obbligatorio" if d["livello_gioco"] else "esplorazione"
    pers.append(d)
ids={p["id"] for p in pers}; lids={l[0] for l in LUOGHI}
for p in pers:
    assert p["luogo_principale"] in lids, p["id"]
    for l in p["luoghi_secondari"]: assert l in lids,(p["id"],l)
    for c in p["personaggi_collegati"]: assert c in ids,(p["id"],c)
    assert p["epoca"] in EPOCHE
luoghi=[dict(id=a,nome=b,hub=c,funzione_hub=d or None,coordinate=None,personaggi=[p["id"] for p in pers if p["luogo_principale"]==a or a in p["luoghi_secondari"]]) for a,b,c,d in LUOGHI]
db=dict(versione="0.1",data="2026-09-28",descrizione="Database storico-culturale dell'anno 1 del videogioco 'I cinque duchi' (Ferrara). Vedi videogioco-5-duchi-anno1-ferrara.md per convenzioni.",
  legenda=dict(legame_luogo={"A":"luogo della vita","B":"luogo dell'opera","C":"luogo della memoria","D":"luogo simbolico","E":"luogo problematico (legame indiretto, leggendario o costruito dopo)"},
    certezza={"D":"documentato","I":"interpretato","M":"memoria","L":"leggenda","F":"figura letteraria","C":"collettivo","?":"suffisso: attribuzione incerta"},
    origine={"Pietro":"scheda del materiale di Pietro","aggiunta":"scheda aggiunta da Claude (personaggio citato nella narrazione o necessario al gioco)","proposta":"proposta di Claude da approvare","Pietro (ricollocato)":"scheda di Pietro con collocazione rivista"}),
  epoche=EPOCHE,luoghi=luoghi,personaggi=pers)
json.dump(db,open("videogioco-5-duchi-anno1-personaggi.json","w"),ensure_ascii=False,indent=1)
from collections import Counter
print(len(pers),"personaggi;",len(luoghi),"luoghi")
print(Counter(p["origine"] for p in pers)); print(Counter(p["ruolo_nel_gioco"] for p in pers))
lv=Counter(p["livello_gioco"] for p in pers if p["livello_gioco"]); print(sorted(lv, key=lambda s:int(s.split('-')[1]))); print(len(lv))
# tabella md
rows=["| ID | Personaggio | Periodo | Epoca | Luogo principale | Legame | Certezza | Livello | Origine |","|---|---|---|---|---|---|---|---|---|"]
LN={a:b for a,b,c,d in LUOGHI}
for p in pers:
    rows.append(f"| {p['id']} | {p['nome']} | {p['periodo']} | {p['epoca']} | {LN[p['luogo_principale']].split(' (')[0]} | {p['legame_luogo']} | {' + '.join(p['certezza'])} | {p['livello_gioco'] or 'esplorazione'} | {p['origine']} |")
open("tabella.md","w").write("\n".join(rows))
lr=["| ID | Luogo | Hub | Personaggi collegati |","|---|---|---|---|"]
for l in luoghi: lr.append(f"| {l['id']} | {l['nome']} | {l['funzione_hub'] or '—'} | {len(l['personaggi'])} |")
open("luoghi.md","w").write("\n".join(lr))
